### PR TITLE
Our Programmes & Events Components

### PR DESCRIPTION
**Pull request by Hackin7**
image

Only the basic UI first, sample content left inside first

https://github.com/AdvisorySG/dawn-advisory-theme/issues/127

### CODE REVIEW

**Comment by Hackin7** [comment]
Mobile UI
image

**Comment by Hackin7** [comment]
image

**Review by wei2912 — CHANGES_REQUESTED** [review]
LGTM overall, but buttons should be replaced by `a` tags instead, as that doesn't require JavaScript.

**Comment by wei2912** [comment]
Merged in https://github.com/AdvisorySG/dawn-advisory-theme/commit/e9a24b80d311a78469dde70c5c82308a49f9ce6e!

**Pull request closed without merging**
