### PR TITLE
[GPT-11] increased font size

### PR DESCRIPTION
**Pull request by ChenSirui-016**

### CODE REVIEW

**Comment by wei2912** [comment]
1. Headings and text of the banners should be left aligned.
2. Vertical space between heading and text should be same as between text and button.
3. Entire content of banner should be vertically centered.

**Comment by jeffzy15** [comment]
Todo:
- [ ] Restyle banners to be in the form of three columns (on desktop), which is more readable than horizontal banners.
- [ ] Headings and text of the banners should be left aligned.
- [ ] Vertical space between heading and text should be same as between text and button.
- [ ] Entire content of banner should be vertically centered.
- [ ] Reduce vertical space between banners

**Comment by jeffzy15** [comment]
New PR: #308

**Comment by Hackin7** [comment]
Will close this since theres a new PR for it

**Pull request closed without merging**
