### PR TITLE
[GPT-12] Meta data aesthetics fix

### PR DESCRIPTION
**Pull request by gajinkee**
Shifted the primary tags below the date and read time as long tags make the line too ugly
Added Margins above addn tags to seperate from the main primary tags.
Experimented with the font size to get the result below.

d3
d2
d1
phone3
phone2
phone1

### CODE REVIEW

**Comment by gajinkee** [comment]
Looks abit like this after changes.

meta2
meta1

**Comment by wei2912** [comment]
1. Consider moving title to top
2. Change to pill tags, remove "More Tags:" and distinction between primary tag and other tags
3. Check for responsive design

**Comment by gajinkee** [comment]
Made the tags into pills.
Looks a lot smoother and is more responsive between screen sizes since there's no distinction between tags anymore
The header at the top also gives the content a more article feel. (included sc with header unchanged for reference)

sc2
sc1

sc3
sc4

**Comment by wei2912** [comment]
Approved with minor changes made in https://github.com/AdvisorySG/dawn-advisory-theme/commit/6fbc9168b4de33b734f50a2be58b172efa3aeaee.

**Pull request closed without merging**
