### PR TITLE
[GPT-88] feat: update footnotes styling 

### PR DESCRIPTION
**Pull request by feliciahmq**
image

### CODE REVIEW

**Review by wei2912 — CHANGES_REQUESTED** [review]
Just some minor stylistic changes:

1. Could the inline footnote be changed from "[1]" to "1"?

image

2. Could "[1]" for the references be changed so that the font size is the same, instead of being a superscript?

image

3. Also, could you remove `display: none` from `.footnote-backref`?

image

**Comment by wei2912** [comment]
Also, can I check if the code was adapted from anywhere?

**Comment by feliciahmq** [comment]
image

I can't seem to remove the brackets. Code for footnote counter is from ChatGPT, code for style adapted from the wordpress website.

**Review by wei2912 — APPROVED** [review]
LGTM, thanks for the PR!

**Pull request merged**
