### PR TITLE
[GPT-125] [GPT-131] Home Page Revamp with Impact Updates

### PR DESCRIPTION
**Pull request by Hackin7**
PCSC Meeting Minutes:
1. Implement the impact numbers section into the new website

2. Quotes section from the beta site to be replaced with the design from KS's mockup. Keep the 3 quotes static. Make sure the header sizes are coherent with the rest of the home page.

3. Update the featured by section of the home page. Update with logos of publications we were recently featured by + directly link to the article webpage itself. 

4. Move the Social Impact Report to 'reports' and the Forbes 30 under 30 to 'Press releases'. 

5. Home page -- Photo banner with a tagline, followed by our mission (refer to Access.sg's website for design and size ratio)
- To find a suitable image 
- To provide Tech with a tagline for the photo banner

6. Implement the Communities and Join Us pages

7. Make all headers the same size ('Featured By', 'Our Partners 'to match the 'Get Involved', 'What we Do')

8. Provide Tech with the images and details for the Team page

### CODE REVIEW

**Comment by Hackin7** [comment]
image
Rough impact section

**Comment by Hackin7** [comment]
Just added in search since it is quite critical/ a quick fix
image

**Comment by Hackin7** [comment]
image

**Comment by Hackin7** [comment]
image

Can probably merge this in first for further review by PCSC, the remaining issues need to be settled by PCSC (eg. starter copywriting)

**Review by wei2912 — APPROVED** [review]
Code looks good, will file separate issues for any other adjustments to be made.

**Pull request merged**
