### PR TITLE
[GPT-112] [GPT-93] Home: Homepage update 3

### PR DESCRIPTION
**Pull request by Hackin7**

### CODE REVIEW

**Comment by Hackin7** [comment]
image

**Review by wei2912 — CHANGES_REQUESTED** [review]
1. Could the search button + the code for search at https://github.com/AdvisorySG/dawn-advisory-theme/blob/main/assets/js/main.js be completely removed (rather than commented out)?
2. Please incorporate https://github.com/AdvisorySG/dawn-advisory-theme/pull/383 into this update too.

**Comment by wei2912** [comment]
Also, there's this remaining matter:

> 
What We Do - Vertically align cards, replace Mentorship photo with the programme logo, other photos to be zoomed out so that text is still visible.

image

Right now the vertical alignment is a bit off.

**Comment by Hackin7** [comment]
Search code commented out to be consistent with the PR for mentorship, as well as to make it easier to reimplement in the future (without needing to trudge through version control)

**Comment by wei2912** [comment]
Manually merged in https://github.com/AdvisorySG/dawn-advisory-theme/commit/cb9aab63d5588da5220b3cab1114703e7fe1449c.

**Pull request closed without merging**
