### PR TITLE
Index: Constrain widths for post cards

### PR DESCRIPTION
**Pull request by Hackin7**
This is still up for discussion, but here are my suggested changes
1. Lower the breakpoint to `sm` (The lowest default breakpoint of )
2. Change the max width of the image on the postcard (on `flex-row`, where everything is arranged sideways) from 40% to 30%

image
image
image

For (1), if desired, we could add a smaller breakpoint
https://tailwindcss.com/docs/screens#adding-smaller-breakpoints

For (2) here are some options

20%
image
image

25%
image

35%
image

### CODE REVIEW

**Review by wei2912 — CHANGES_REQUESTED** [review]
Some comments:
1. The current aspect ratio of the "frame" (e.g. https://s3-ap-southeast-1.amazonaws.com/advisorysg-ghost/2021/10/34.png) has been standardised to 1200x627 (1.91:1), and will be used across all articles. To ensure the text and logo isn't cut off, the image should not be resized smaller than 1080x627 (1.72:1), and should be centered when resized.
2. Not sure how this will affect when to trigger the breakpoints, let me know if you have any thoughts!

**Comment by Hackin7** [comment]
I'm not really sure how to resolve this, I've tested a bit and thought of 2 possible ideas
1. For the card with the image at the side, we
  -  Still lower the breakpoint to sm (so cards don't become too wide)
  - Change the image width at different breakpoints. From sm to md, image width could be 50%, from md onwards, image could remain same at 40% (no issues)
2. Increase the height of the image at the smallest width (for now I tested h-72, I think h-80 makes the image too tall)
  - Not sure if this is necessary since this would be an extreme edge case

Image width at 40%

image

Image Width at 50%

image

Increase Height of Card

image

image

**Comment by Hackin7** [comment]
image
image
image

Added a max width for post cards on mobile

**Comment by wei2912** [comment]
@Hackin7 I came up with a few changes, do you mind seeing if these are good? Just replace the respective lines in `post-card.hbs` with the following:

```html
<article class="feed-card {{post_class}} rounded-lg ring-1 ring-gray-900/5 shadow-xl m-auto w-full max-w-2xl md:max-w-full lg:h-full hover:shadow-md hover:border-opacity-0 transform hover:-translate-y-1 transition-all duration-200">
    <div onclick="location.href='{{url}}'" class="flex flex-col cursor-pointer h-full rounded-xl overflow-hidden md:flex-row md:h-80 lg:flex-col lg:h-full">
        {{#if feature_image}}
        <img class="object-cover m-0 h-full md:aspect-[9/5] lg:h-auto lg:aspect-[15/8]" src="{{img_url feature_image}}" alt="{{title}}" />
        {{else}} {{!-- Placeholder --}}
        <img class="object-cover m-0 hidden h-48 md:aspect-[9/5] lg:aspect-[15/8]" src="https://via.placeholder.com/100/FFFFFF/FFFFFF" alt="{{title}}" />
        {{/if}}
        <div class="grow bg-white px-3 pt-3 pb-5 relative">
```

**Comment by Hackin7** [comment]
The changes look great!

image
image

**Comment by wei2912** [comment]
Thanks! Will merge in that case.

**Review by wei2912 — APPROVED** [review]

**Pull request merged**
