### PR TITLE
[GPT-96] Home page revamp 2

### PR DESCRIPTION
**Pull request by Hackin7**
Fixed (1), (2)

### CODE REVIEW

**Comment by Hackin7** [comment]
image

Ideas
1. for Highlights, reuse featured-articles feature - but link to a custom property
2. Rename Featured Articles to Highlights using tag settings

Mobile view is something to take note of also

**Comment by Hackin7** [comment]
Tested Repurposing the Featured Articles Section for Highlights Carousel, I think it looks well
Events, Mentorship, Conversations etc.
Website Managers can just update the featured articles to update the relevant content easily

image

image

image

**Comment by Hackin7** [comment]
Sample concept of using the Insights tag (making it public) 
The page people are redirected to after clicking on Events

image

**Comment by wei2912** [comment]
For separation of Impact posts, please use the collection feature - https://ghost.org/docs/themes/routing/#collections
Should work with private tags, just make sure the `routes.yaml` is made available. (There's no automatic way to deploy this yet so we gotta upload it separately, and on Telegram too as backup.)

**Comment by Hackin7** [comment]
ghost collections are exclusive btw - if we set a collection for insight posts, the collection for the stories page would exclude the insight posts

**Comment by Hackin7** [comment]
image

**Review by wei2912 — APPROVED** [review]
Please proceed to merge (after optimising the `png` using https://superuser.com/questions/956288/how-do-i-use-optipng-on-windows-to-get-a-lossless-file) and set up the `routes.yaml` + sample highlights (please keep stories as they are, assign events the `#event` tag and the rest the `#highlight` tag).

**Comment by Hackin7** [comment]
Just merged it in first - to be iterated on further

**Pull request merged**
