### PR TITLE
Author: Display placeholder profile pic #18

### PR DESCRIPTION
**Pull request by Ishneet0710**

### CODE REVIEW

**Review by partysnax — CHANGES_REQUESTED** [review]
1. I think some sort of check has to be done if the author does have an image of their own, because the placeholder is shown in place of their own image instead.
2. It'll be good if the placeholder image URL is replaced with a local file that's copyright free.
3. It'll be nice if the placeholder image for the author is also shown at the bottom of the post page, i.e. in `partials\content.hbs` at line 87.

Thanks

**Comment by Ishneet0710** [comment]
i have made the necessary changes. you can double check before merging

**Review by partysnax — CHANGES_REQUESTED** [review]
Thanks for the work. Just a couple of minor issues before we can merge it in:

1. In both `content.hbs` and `author.hbs` , the placeholder image should be a clickable link that directs the user to the author's page, to maintain consistency in behaviour with the cases where a profile image exists.
2. The placeholder image loads correctly in `content.hbs` but not `author.hbs` . For the latter, check the routing of the image URL, I believe another `../` in front is needed there. Alternatively, consider using the [asset helper](https://ghost.org/docs/themes/helpers/asset/).

**Comment by Ishneet0710** [comment]
i have fixed the minor changes. thanks!

**Comment by wei2912** [comment]
Sorry @Ishneet0710, I have two other changes to suggest before merging :sweat_smile: 
1. Please use the asset helper as suggested by @partysnax, to be consistent across the rest of the theme files.
2. Actually, it's not necessary to modify `partials/content.hbs` as https://github.com/AdvisorySG/dawn-advisory-theme/pull/47 compresses the list of authors into a single line. Feel free to leave the code in that file unchanged, I'll deal with it when merging.

This PR should be merged only after https://github.com/AdvisorySG/dawn-advisory-theme/pull/47 is merged.

**Comment by wei2912** [comment]
https://github.com/AdvisorySG/dawn-advisory-theme/pull/47 blocks this PR.

**Review by partysnax — APPROVED** [review]

**Comment by wei2912** [comment]
This PR was accidentally merged, needs to be remerged after the blocking issue is cleared.

**Comment by wei2912** [comment]
Merged again in https://github.com/AdvisorySG/dawn-advisory-theme/commit/16adb68d4cf0b5083181c5b6f4e369e642bde79e.

**Pull request merged**
