### PR TITLE
[GPT-44] Stories: Blue Border on cards

### PR DESCRIPTION
**Pull request by jeffzy15**
Replaced the blue border with gray border

image

### CODE REVIEW

**Review by Hackin7 — CHANGES_REQUESTED** [review]
Can we try removing the border on the cards entirely?

**Comment by jeffzy15** [comment]
Without borders
image

With borders
image

**Comment by Aelderic** [comment]
Explore the idea of using borderless cards but amend the shadow

**Comment by Hackin7** [comment]
Reviewer just edit shadow to shadow-2xl,
We might want to add a shadow at the top of the cards, but we will play by ear according to management

**Review by Hackin7 — APPROVED** [review]
Just darkened the shadow, other than that LGTM!

**Pull request merged**
