### PR TITLE
[GPT-10] Figuring out the best way to handle a chunk of text

### PR DESCRIPTION
**Pull request by Hackin7**
One way I tested is by making the tags expanable/collapsible - this would make the large amount of tags easier to handle in a way

image
image

however, the tags are still kind of messy,  To be worked on to check for better ways to handle this

### CODE REVIEW

**Comment by Hackin7** [comment]
Experimenting with tags
image

image

For now I settled on this colour, to be discussed further

image

**Comment by Hackin7** [comment]
Tried to strike a better balance between colours
image

**Comment by wei2912** [comment]
To remove "Industries:" and just display all tags.

We may want to style the tags a bit differently, not sure how...

**Comment by Hackin7** [comment]
image

For now I didn't configure the colouring of tags yet (besides preparing the base code), should be done only after we confirm what tags there are, so we can manually customise & curate. Another option is to randomised, which may not be preferred.

**Review by wei2912 — DISMISSED** [review]
LGTM! Please proceed to merge after resolving the conflicts.

**Review by wei2912 — CHANGES_REQUESTED** [review]
There's some accidental copy paste in the files.

**Pull request merged**
