### PR TITLE
Adding postcards, as well as replacing post list with post cards

### PR DESCRIPTION
**Pull request by Hackin7**
Add & modify postcards, Modify related.hbs and index.hbs to support postcards

The main things done are
1. The addition of a postcard partial. This is modified to work properly. Some changes include
    1. Adding appropriate text & background colours for light and dark mode
    2. Making it compatible with the feed on the main page

2. The feed of the main page is updated to use the post-cards. The related javascript code is also modified to make the formatting & the load more function work. For now, 5 cards are shown at once, but this could potentially be modified down the road

image

image

image

3. The related articles are changed to also use postcards

image

image

`partials/loop.hbs` is kept for legacy purposes, but it should be able to be removed if needed.

### CODE REVIEW

**Comment by wei2912** [comment]
Just a few comments:
1. Marketing has agreed on a 3-column layout for the cards. Please check if this changes to a 2-column or 1-column layout on smaller width devices, thanks!
2. Tags should be of the accent colour and capitalised, similar to how it displays on posts.
3. `fa-clock` icon is not rendering, please include Font Awesome in `default.html` using the following:
```
<script src="https://kit.fontawesome.com/c5d20f06dc.js" crossorigin="anonymous"></script>
```
4. Do remove `partials/loop.hbs`; if needed we can always refer to the relevant commits.
5. The "Load More" button should load posts in multiples of 3.
6. If there is no tag for the article, a placeholder should be displayed instead, e.g. "[No tag]". This placeholder should be the same colour as normal text, so that it can be easily distinguished from actual tags (which will have the accent colour of the theme).

Otherwise, looks good overall!

**Review by wei2912 — CHANGES_REQUESTED** [review]
See above.

**Comment by Hackin7** [comment]
Tried Testing dark coloured cards

image

Most of the points should have been addressed except point 5, still working on it

**Comment by wei2912** [comment]
@Hackin7 On point 5, perhaps we could go with 6 posts at a time for now and change that based on how our feedback from UI testing turns out. That should take place in Q1 of next year.

**Comment by wei2912** [comment]
Squashed and merged in https://github.com/AdvisorySG/dawn-advisory-theme/commit/6f1c54398dc499797e865a243b9c4ece682b30f6, with some amendments.

**Pull request closed without merging**
