### PR TITLE
[GPT-35] 267 footer image cannot be seen

### PR DESCRIPTION
**Pull request by bryanseah234**
changed footer color to black

### CODE REVIEW

**Review by Hackin7 — CHANGES_REQUESTED** [review]
image

Hmm now the text is not visible
Can you make the text white/ more visible?

**Comment by gajinkee** [comment]
Looks like this now

image

**Comment by wei2912** [comment]
@gajinkee how about the "Powered by Ghost" part lol

**Comment by gajinkee** [comment]
Oh my bad did not see it haha. Fixed it here.
image

**Pull request merged**
