### PR TITLE
[GPT-75] Home page revamp

### PR DESCRIPTION
**Pull request by Hackin7**
Structuring and Revamping the Home Page

Main Deliverable of PR: Home page ready for revetting that has the required sections such as
1. About us
2. Impact
3. Getting Involved

### CODE REVIEW

**Comment by Hackin7** [comment]
image

Rough layout of the Join Us Section

**Comment by Hackin7** [comment]
image

**Comment by Hackin7** [comment]
Potential Impact Section
image

**Comment by wei2912** [comment]
To check if https://linear.app/advisorysg/issue/GPT-72/website-can-be-scrolled-horizontally still occurs when merging.

**Pull request merged**
