### PR TITLE
[GPT-103] [GPT-106] [Insights] Switch insights page styling + padding for (Stories & Insights)button

### PR DESCRIPTION
**Pull request by Hackin7**
image

image

### CODE REVIEW

**Comment by Hackin7** [comment]
Realised the issue was talking about all pages so I modified `footer.hbs` instead of `pagination.hbs`
image
image
image

**Comment by Hackin7** [comment]
image

I think this is passable for website launch, we can add additional features

Other notes
1. flowbite was used as I think its a good way to import components quickly/ reduce dev time, so that we can focus less on reimplementing and more on design - need to create an issue for documentation

**Review by wei2912 — CHANGES_REQUESTED** [review]
LGTM - but could we increase the font size of the dropdown to `text-xl`?

**Comment by Hackin7** [comment]
image

**Comment by wei2912** [comment]
Merged in https://github.com/AdvisorySG/dawn-advisory-theme/commit/711d98815fff8ff1a493ed23bc754522ea8f7280, manually uploading `routes.yaml`.

**Pull request closed without merging**
